modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/abnormals-delight/issues"
license = "https://github.com/team-abnormals/abnormals-delight/blob/main/LICENSE.txt"

[[mods]]
    modId = "abnormals_delight"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "abnormals_delight:strawberry_cake_slice"
    configBackground = "abnormals_delight:textures/block/terracotta_bricks.png"
    authors = "Team Abnormals"
    credits = "bageldotjpg, five"
    displayURL = "https://www.teamabnormals.com/mods/abnormals-delight"
    displayName = "Abnormals Delight"
    description = '''
    Adds compatibility between mods by Team Abnormals and Farmer's Delight by vectorwing.
    Includes cabinets, cake slices, and some basic cutting & cooking recipes.
    '''

[[dependencies.abnormals_delight]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.1,1.19)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.abnormals_delight]]
    modId = "forge"
    mandatory = true
    versionRange = "[39.0.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.abnormals_delight]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[5.0.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.abnormals_delight]]
    modId = "farmersdelight"
    mandatory = true
    versionRange = "[1.0.0,)"
    ordering = "AFTER"
    side = "BOTH"